package com.example.demo.Entities.RelationEntites;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class managesID implements java.io.Serializable {

    @Column(name = "manager_id")
    private Integer manager_id;

    @Column(name = "shelter_id")
    private Integer shelter_id;

    // Constructors, getters, and setters (if not generated by Lombok)...
}
