package com.example.demo.Entities.RelationEntites;

import com.example.demo.Entities.AccountEntites.shelter;
import com.example.demo.Entities.PetEntities.pet;
import jakarta.persistence.Column;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class sheltered_atID implements java.io.Serializable {

        @Column(name = "pet_id")
        private Integer pet_id;

        @Column(name = "shelter_id")
        private Integer shelter_id;

        // Constructors, getters, and setters (if not generated by Lombok)...
}
