package com.example.demo.Entities;

import jakarta.persistence.Embeddable;

@Embeddable
public class managesID {
    private Integer manager_id;
    private Integer shelter_id;

    // Constructors, getters, and setters (if not generated by Lombok)...
}
