package com.example.demo.Entities.RecordsEntities;

import com.example.demo.Entities.AccountEntites.adopter;
import com.example.demo.Entities.AccountEntites.shelter;
import com.example.demo.Entities.PetEntities.pet;
import jakarta.persistence.Column;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class adoption_applicationID implements java.io.Serializable{

        @Column(name = "adopter_id")
        private int adopter_id;

        @Column(name = "pet_id")
        private int pet_id;

        @Column(name = "shelter_id")
        private int shelter_id;

        // Constructors, getters, and setters (if not generated by Lombok)...
}
